alias ..='cd ..'
alias gh='history | grep'
alias ls='ls --color=auto'
alias ll='ls -lha'
alias grep='grep --color=auto'
alias mkdir='mkdir -p'
alias df='df -H'
alias du='du -ch'
alias c='clear'
alias vi='vim'
alias nano='vim'
alias php7='/usr/bin/php7.4'
alias php8='/usr/bin/php8.1'
alias mylocalip='hostname -I | awk "{print $1}"'
alias mypublicip='curl ifconfig.me'
