#!/bin/bash

# The return value of a pipeline is the status of
# the last command to exit with a non-zero status,
# or zero if no command exited with a non-zero status
set -o pipefail
set -o nounset # Treat unset variables as an error when substituting.
set -o errexit # Exit immediately if a command exits with a non-zero status.

if [ "$(id -u)" != "0" ]; then
   echo -e "This script must be run as root." 1>&2
   exit 1
fi

REPOS_DIR="/home/${SUDO_USER}/repos"
DOTFILES_DIR="${REPOS_DIR}/.dotfiles"

if [ ! -d "${DOTFILES_DIR}" ]; then
    if [ ! -d "${REPOS_DIR}" ]; then
        mkdir -p "${REPOS_DIR}"
    fi

    apt install git
    git clone https://github.com/f-pisani/.dotfiles.git "${DOTFILES_DIR}"
    git remote remove origin
    git remote add git@github.com:f-pisani/.dotfiles.git
    chown -R "${SUDO_USER}":"${SUDO_USER}" "${DOTFILES_DIR}"
fi

bash "${DOTFILES_DIR}/install"
