#!/bin/bash

# The return value of a pipeline is the status of
# the last command to exit with a non-zero status,
# or zero if no command exited with a non-zero status
set -o pipefail
set -o nounset # Treat unset variables as an error when substituting.
set -o errexit # Exit immediately if a command exits with a non-zero status.

DIR=$([[ $(realpath "$0") =~ (.+/.dotfiles) ]] && echo "${BASH_REMATCH[1]}")
source "${DIR}/must_be_run_as_root"

# shellcheck disable=SC2045
for FILE in $(ls "${DIR}/post_install.d/")
do
  POST_INSTALL_SCRIPT="${DIR}/post_install.d/${FILE}"
  echo -e "${YELLOW}Executing ${POST_INSTALL_SCRIPT} ...${ENDCOLOR}"
  . "${POST_INSTALL_SCRIPT}"
  echo -e "${YELLOW}${POST_INSTALL_SCRIPT} executed.${ENDCOLOR}"
done
