#!/bin/bash

# The return value of a pipeline is the status of
# the last command to exit with a non-zero status,
# or zero if no command exited with a non-zero status
set -o pipefail
set -o nounset # Treat unset variables as an error when substituting.
set -o errexit # Exit immediately if a command exits with a non-zero status.

DIR=$([[ $(realpath "$0") =~ (.+/.dotfiles) ]] && echo "${BASH_REMATCH[1]}")
source "${DIR}/must_be_run_as_root"

echo -e "${GREEN}$(figlet "System Hardening")${ENDCOLOR}"

echo -e "${YELLOW}Applying system hardening ...${ENDCOLOR}"
apt install -y apt-listbugs libpam-tmpdir needrestart debsecan debsums fail2ban
chmod 750 /home/*
echo -e "${YELLOW}System hardening applied.${ENDCOLOR}"