#!/bin/bash

# The return value of a pipeline is the status of
# the last command to exit with a non-zero status,
# or zero if no command exited with a non-zero status
set -o pipefail
set -o nounset # Treat unset variables as an error when substituting.
set -o errexit # Exit immediately if a command exits with a non-zero status.

DIR=$([[ $(realpath "$0") =~ (.+/.dotfiles) ]] && echo "${BASH_REMATCH[1]}")
source "$DIR/lib/must_be_run_as_root"

echo -e "${BIGREEN}$(figlet "Yubikey")${NC}"

echo -e "${BIYELLOW}Installing YubiKey tools...${NC}"
apt install -y wget gnupg2 gnupg-agent dirmngr cryptsetup scdaemon pcscd \
               secure-delete hopenpgp-tools yubikey-personalization \
               python3-pip python3-pyscard pinentry-gnome3
pip3 install PyOpenSSL yubikey-manager
service pcscd start
echo -e "${BIYELLOW}YubiKey tools installed.${NC}"

if [ ! -d "/home/${SUDO_USER}/.gnupg" ]; then
    mkdir -p "/home/${SUDO_USER}/.gnupg"
fi
echo -e "enable-ssh-support\npinentry-program /usr/bin/pinentry-x11" > "/home/${SUDO_USER}/.gnupg/gpg-agent.conf"
chown -R "${SUDO_USER}":"${SUDO_USER}" "/home/${SUDO_USER}/.gnupg"
