#!/bin/bash

# The return value of a pipeline is the status of
# the last command to exit with a non-zero status,
# or zero if no command exited with a non-zero status
set -o pipefail
set -o nounset # Treat unset variables as an error when substituting.
set -o errexit # Exit immediately if a command exits with a non-zero status.

DIR=$([[ $(realpath "$0") =~ (.+/.dotfiles) ]] && echo "${BASH_REMATCH[1]}")
source "${DIR}/must_be_run_as_root"

echo -e "${BIGREEN}$(figlet "Drivers")${NC}"

echo -e "${BIYELLOW}Installing drivers...${NC}"
apt install -y firmware-linux firmware-linux-free firmware-misc-nonfree firmware-iwlwifi
echo -e "${BIYELLOW}Drivers installed.${NC}"
