#!/bin/bash

# The return value of a pipeline is the status of
# the last command to exit with a non-zero status,
# or zero if no command exited with a non-zero status
set -o pipefail
set -o nounset # Treat unset variables as an error when substituting.
set -o errexit # Exit immediately if a command exits with a non-zero status.

DIR=$([[ $(realpath "$0") =~ (.+/.dotfiles) ]] && echo "${BASH_REMATCH[1]}")
source "$DIR/lib/must_be_run_as_root"

function add_apt_source() {
  SOURCE_NAME="$1"
  GPG_URL="$2"
  APT_SOURCE="$3"
  KEYRING_FILE="/etc/apt/keyrings/$SOURCE_NAME.gpg"
  APT_SOURCE_FILE="/etc/apt/sources.list.d/$SOURCE_NAME.list"

  if [ ! -f "$KEYRING_FILE" ]; then
    mkdir -p /etc/apt/keyrings
    curl -fsSL "$GPG_URL" | gpg --dearmor --batch --yes -o "$KEYRING_FILE"
    echo "$APT_SOURCE" | tee "$APT_SOURCE_FILE" > /dev/null
    apt update
  fi
}
